# Uncomment the lines below you want to change by removing the # in the beginning
ios_version '11.0.1'


# A list of devices you want to take the screenshots from
 devices([
   "iPhone 7 Plus",
   "iPhone XS Max",
   "iPad Pro (12.9-inch) (1st generation)",
   "iPad Pro (12.9-inch) (2nd generation)",
   "iPad Pro (12.9-inch) (3rd generation)",
#   "Apple TV 1080p",

 ])
languages([
   "en-US",
   "de-DE",
   "it",

#   ["pt", "pt_BR"] # Portuguese with Brazilian locale
 ])

# The name of the scheme which contains the UI Tests
 scheme("RxConvert UITests")

# Where should the resulting screenshots be stored?
output_directory "./fastlane/screenshots/#{ENV['SCHEME']}"

# remove the '#' to clear all previously generated screenshots before creating new ones
clear_previous_screenshots(true)

# Remove the '#' to set the status bar to 9:41 AM, and show full battery and reception.
# override_status_bar(true)

# Arguments to pass to the app on launch. See https://docs.fastlane.tools/actions/snapshot/#launch-arguments
# launch_arguments(["-favColor red"])

# For more information about all available options run
# fastlane action snapshot
